-- Run with a selected database, for example:
-- mysql -uroot -D stock_analysis_test < sql/2026-06-19-create-ai-etf.sql

CREATE TABLE IF NOT EXISTS stock_ai_etf_snapshot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  portfolio_name VARCHAR(64) NOT NULL DEFAULT 'AI_RECOMMENDED_ETF' COMMENT '组合名称',
  trade_date DATE NOT NULL COMMENT '组合生成/调仓交易日',
  adjust_type ENUM('none','qfq','hfq') NOT NULL DEFAULT 'qfq',
  selection_rule VARCHAR(1024) NULL COMMENT '本次选股与调仓规则摘要',
  nav DECIMAL(24,6) NULL COMMENT '模拟组合净值/总资产',
  daily_return_pct DECIMAL(12,6) NULL COMMENT '当日收益率，百分比数值',
  cumulative_return_pct DECIMAL(12,6) NULL COMMENT '累计收益率，百分比数值',
  realized_pnl DECIMAL(24,6) NULL COMMENT '已实现盈亏',
  unrealized_pnl DECIMAL(24,6) NULL COMMENT '未实现盈亏',
  total_pnl DECIMAL(24,6) NULL COMMENT '总盈亏',
  turnover_pct DECIMAL(12,6) NULL COMMENT '本次调仓换手率，百分比数值',
  holding_count SMALLINT NOT NULL DEFAULT 0 COMMENT '目标持仓数量',
  summary_json JSON NULL COMMENT '组合摘要、风险集中度等结构化信息',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_ai_etf_snapshot (portfolio_name, trade_date, adjust_type),
  KEY idx_stock_ai_etf_snapshot_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI推荐ETF每日组合快照';

CREATE TABLE IF NOT EXISTS stock_ai_etf_holding (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  portfolio_name VARCHAR(64) NOT NULL DEFAULT 'AI_RECOMMENDED_ETF',
  trade_date DATE NOT NULL,
  adjust_type ENUM('none','qfq','hfq') NOT NULL DEFAULT 'qfq',
  stock_code VARCHAR(16) NOT NULL,
  stock_name VARCHAR(64) NULL,
  industry VARCHAR(128) NULL,
  previous_weight_pct DECIMAL(12,6) NULL COMMENT '调仓前权重，百分比数值',
  target_weight_pct DECIMAL(12,6) NOT NULL COMMENT '调仓后目标权重，百分比数值',
  weight_delta_pct DECIMAL(12,6) NULL COMMENT '目标权重变化，百分比数值',
  action ENUM('buy','sell','increase','reduce','hold','watch') NOT NULL COMMENT '本次仓位动作',
  reference_price DECIMAL(18,4) NULL COMMENT '调仓参考价格',
  simulated_quantity DECIMAL(24,6) NULL COMMENT '模拟持仓数量',
  simulated_notional DECIMAL(24,6) NULL COMMENT '模拟持仓市值',
  score INT NULL,
  signal_label VARCHAR(32) NULL,
  short_term_score INT NULL,
  short_term_signal_label VARCHAR(32) NULL,
  medium_term_score INT NULL,
  medium_term_signal_label VARCHAR(32) NULL,
  long_term_score INT NULL,
  long_term_signal_label VARCHAR(32) NULL,
  confidence VARCHAR(16) NULL,
  rationale VARCHAR(1024) NULL COMMENT '纳入/调仓理由',
  risks_json JSON NULL COMMENT '组合层风险提示',
  raw_json JSON NULL COMMENT '原始持仓快照',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_ai_etf_holding (portfolio_name, trade_date, adjust_type, stock_code),
  KEY idx_stock_ai_etf_holding_date (trade_date, target_weight_pct),
  KEY idx_stock_ai_etf_holding_stock (stock_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI推荐ETF持仓与动作明细';

CREATE TABLE IF NOT EXISTS stock_ai_etf_trade (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  portfolio_name VARCHAR(64) NOT NULL DEFAULT 'AI_RECOMMENDED_ETF',
  trade_date DATE NOT NULL,
  adjust_type ENUM('none','qfq','hfq') NOT NULL DEFAULT 'qfq',
  stock_code VARCHAR(16) NOT NULL,
  stock_name VARCHAR(64) NULL,
  action ENUM('buy','sell','increase','reduce','hold','watch') NOT NULL COMMENT '调仓动作',
  previous_weight_pct DECIMAL(12,6) NULL,
  target_weight_pct DECIMAL(12,6) NULL,
  weight_delta_pct DECIMAL(12,6) NULL,
  reference_price DECIMAL(18,4) NULL,
  simulated_quantity_delta DECIMAL(24,6) NULL COMMENT '本次模拟数量变化',
  simulated_notional_delta DECIMAL(24,6) NULL COMMENT '本次模拟金额变化',
  realized_pnl DECIMAL(24,6) NULL,
  realized_return_pct DECIMAL(12,6) NULL,
  reason VARCHAR(1024) NULL,
  raw_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_ai_etf_trade (portfolio_name, trade_date, adjust_type, stock_code, action),
  KEY idx_stock_ai_etf_trade_date (trade_date, action),
  KEY idx_stock_ai_etf_trade_stock (stock_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI推荐ETF模拟调仓与盈亏记录';
